inherit_from:
  - https://raw.githubusercontent.com/rails/rails/master/.rubocop.yml

AllCops:
  Rails:
    Enabled: true
  Exclude:
    - gakubuchi.gemspec
    - spec/dummy/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb

LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: normal
