language: ruby
sudo: false
rvm:
  - 2.0
  - 2.1.9
  - 2.2.6
  - 2.3.3
gemfile:
  - gemfiles/sprockets_rails_2_with_sprockets_2.gemfile
  - gemfiles/sprockets_rails_2_with_sprockets_3.gemfile
  - gemfiles/sprockets_rails_3_with_sprockets_3.gemfile
matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/sprockets_rails_3_with_sprockets_3.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/sprockets_rails_3_with_sprockets_3.gemfile
branches:
  only:
    - master
after_script:
  - bundle exec codeclimate-test-reporter
